<?php

namespace MainBundle\Repository;

/**
 * favouriteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class favouriteRepository extends \Doctrine\ORM\EntityRepository
{
}
