main_homepage:
    path:     /
    defaults: { _controller: MainBundle:Default:index }

main_movies:
    path:     /movies/{id}
    defaults: { _controller: MainBundle:Default:movies }
    # requirements:
    # id: \d+


main_register:
    path:     /register
    defaults: { _controller: MainBundle:Default:register }
    # requirements:
    # id: \d+
