main_homepage:
    path:     /
    defaults: { _controller: MainBundle:Default:index }

main_movies:
    path:     /movies/{id}
    defaults: { _controller: MainBundle:Default:movies }
    # requirements:
    # id: \d+


main_register:
    path:     /register
    defaults: { _controller: MainBundle:Default:register }


main_login:
    path:     /login
    defaults: { _controller: MainBundle:Default:login }

main_logout:
    path:     /logout
    defaults: { _controller: MainBundle:Default:logout }


main_favourite:
    path:     /favourite
    defaults: { _controller: MainBundle:Default:favourite }

